### ISSUE TITLE
Poco errors from command line build in Ubuntu 15.10

### ISSUE THREAD

**Issue by K0j0** [openframeworks/projectGenerator#71]
I tried running make from the commandLine folder but ran into a bunch of Poco errors. Here's some of them.

`obj/linux64/Release/src/main.o: In function 'main':
main.cpp:(.text.startup+0x106b): undefined reference to 'Poco::Path::current[abi:cxx11]()'
main.cpp:(.text.startup+0x112c): undefined reference to 'Poco::Path::current[abi:cxx11]()'
main.cpp:(.text.startup+0x1141): undefined reference to 'Poco::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text.startup+0x116d): undefined reference to 'Poco::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text.startup+0x1192): undefined reference to 'Poco::Path::toString[abi:cxx11]() const'
main.cpp:(.text.startup+0x11dd): undefined reference to 'Poco::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text.startup+0x1212): undefined reference to 'Poco::Path::toString[abi:cxx11]() const'
main.cpp:(.text.startup+0x2d92): undefined reference to 'Poco::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text.startup+0x2dbc): undefined reference to 'Poco::Path::toString[abi:cxx11]() const'
/home/kojo/dev/ofxPG/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/addons/ofAddon.o: In function 'ofAddon::exclude(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)':
ofAddon.cpp:(.text+0x93c): undefined reference to 'Poco::RegularExpression::RegularExpression(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool)'
ofAddon.cpp:(.text+0xb34): undefined reference to 'Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
ofAddon.cpp:(.text+0xc77): undefined reference to 'Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
ofAddon.cpp:(.text+0xdaf): undefined reference to 'Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
ofAddon.cpp:(.text+0xef4): undefined reference to 'Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
ofAddon.cpp:(.text+0x121e): undefined reference to 'Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
/home/kojo/dev/ofxPG/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/addons/ofAddon.o:ofAddon.cpp:(.text+0x14a1): more undefined references to 'Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const' follow`

It just keeps going. I've run into a similar problem trying to build an existing project. I keep getting Poco errors. OpenFrameworks builds fine by itself but I can't build an existing project or the PG.

**Comment by arturoc** [comment]
if you run the install_dependencies script it'll recompile poco with the new version of gcc, which will fix this errors. it's just an incompatibility problem with libraries compiled with gcc4 in gcc5 the only way to fix it is to recompile the library.
